Iter20
andreevym/metric-collector pull request #14
Opened 2024-03-30 12:19 UTC by andreevym

2024-04-02 14:28 UTC, maxlyaptsev requested changes

2024-04-02 14:28 UTC, maxlyaptsev commented on cmd/staticlint/noexitchecker/check.go
> +func FindOsExitInMain(file ast.Node) *token.Pos {
неверное расположение анализатора
описание стандартных директорий можно почитать например тут https://github.com/golang-standards/project-layout?tab=readme-ov-file#cmd или в первых уроках курса

2024-04-02 14:28 UTC, maxlyaptsev commented on cmd/staticlint/noexitchecker/check.go
> +					return false
чтобы не было такого огромного количества вложений нужно просто инвертировать условие. Подробно о подобных вещах можно почитать в книге "чистый код". Такие условия нечитаемы и глазами сложно найти ошибку

2024-04-02 20:57 UTC, andreevym commented on cmd/staticlint/noexitchecker/check.go
> +					return false
исправлено

2024-04-02 21:00 UTC, andreevym commented on cmd/staticlint/noexitchecker/check.go
> +func FindOsExitInMain(file ast.Node) *token.Pos {
исправлено

2024-04-04 17:11 UTC, maxlyaptsev commented on internal/noexitchecker/check.go
> +package noexitchecker
пакет лежит на верхнем уровне наряду с handlers, storage и middleware - кажется пакет не настолько важный. Конкретно этот пакет лучше конечно смотрелся бы в pkg, а в будущем в отдельном репозитории, который бы подключался как и другие анализаторы

2024-04-04 17:21 UTC, andreevym commented on internal/noexitchecker/check.go
> +package noexitchecker
также считаю, что этому проекту, как и пакету не место в этом репозитории, но как я понимаю это требование этих курсов. для того чтобы было удобно его переносить я изначально расположил всё содержимое в cmd чтобы всё одним пакетом перенести в другой репозиторий.

2024-04-04 19:23 UTC, andreevym commented on internal/noexitchecker/check.go
> +package noexitchecker
перенес в pkg

2024-04-04 21:52 UTC, merged