Iter24 added validation agent header X-Real-IP by server env TRUSTED_SUBNET
andreevym/metric-collector pull request #18
Opened 2024-07-21 22:53 UTC by andreevym

2024-07-30 22:29 UTC, avhitrov requested changes
Функционал шифрования ключами и проверки доступа по X-Real-IP норм. Есть вопросы по организации graceful shutdown, по реализации функции Backup и по разбросанным внутри кода паникам. Все в комментариях к коду.

2024-07-30 22:29 UTC, avhitrov commented on internal/config/agent.go
>  func (c *AgentConfig) Init() *AgentConfig {
```suggestion
func (c *AgentConfig) Init() (*AgentConfig, error) {
```

2024-07-30 22:29 UTC, avhitrov commented on internal/config/agent.go
>  		panic(fmt.Errorf("failed to parse config: %w", err))
```suggestion
		return nil, fmt.Errorf("failed to parse config: %w", err)
```

2024-07-30 22:29 UTC, avhitrov commented on internal/config/server.go
>  func (c *ServerConfig) Init() *ServerConfig {
```suggestion
func (c *ServerConfig) Init() (*ServerConfig, error) {
```

2024-07-30 22:29 UTC, avhitrov commented on internal/config/server.go
> +			panic(fmt.Errorf("failed to read config file '%s': %w", configPath, err))
```suggestion
			return nil, fmt.Errorf("failed to read config file '%s': %w", configPath, err)
```

2024-07-30 22:29 UTC, avhitrov commented on internal/storage/store/store.go
> +	Backup() error
По реализации этой функции есть много вопросов:
1. Каждый ее вызов запускает внутри себя горутину, которая начинает сбрасывать на диск содержимое in-memory стораджа.
2. Эта функция дергается при каждом сохранении данных в in-mem. Причем, если `StoreInterval` выставлен в ноль, то вообще ничего не происходит (а должно происходить сохранение на диск). А если `StoreInterval` выставлен в `> 0`, то при каждом сохранении данных в in-mem запускается еще одна горутина сохранения на диск, в итоге их может стать очень много.
3. В случае недоступности файла бекапа, конфликте доступа и любой ошибке записи дергается `panic()`, из-за чего сервер может просто рухнуть. https://t.me/bushigo/10
4. Запущенную горутину необходимо останавливать при graceful shutdown и дожидаться этой остановки.

По хорошему функцию Backup необходимо разделить на две: Backup и BackupPeriodically. Первую дергать при любом сохранении (проверив предварительно, что `StoreInterval == 0`) и в момент graceful shutdown. Вторую необходимо останавливать в процессе graceful shutdown, если она была запущена, и дождаться ее остановки.

2024-08-23 08:43 UTC, andreevym commented on internal/config/agent.go
>  func (c *AgentConfig) Init() *AgentConfig {
готово

2024-08-23 08:43 UTC, andreevym commented on internal/config/agent.go
>  		panic(fmt.Errorf("failed to parse config: %w", err))
готово

2024-08-23 08:43 UTC, andreevym commented on internal/config/server.go
>  func (c *ServerConfig) Init() *ServerConfig {
готово

2024-08-23 08:43 UTC, andreevym commented on internal/config/server.go
> +			panic(fmt.Errorf("failed to read config file '%s': %w", configPath, err))
готово

2024-08-23 08:43 UTC, andreevym commented on internal/storage/store/store.go
> +	Backup() error
готово

2024-08-24 22:47 UTC, avhitrov approved these changes
Аппрувлю, но есть два замечания по организации бекапа, их обязательно следует учесть в следующей итерации.

2024-08-24 22:47 UTC, avhitrov commented on internal/storage/mem/mem.go
> +	if s.opt == nil || s.opt.BackupPath == "" || s.opt.StoreInterval == 0 {
```suggestion
	if s.opt == nil || s.opt.BackupPath == "" || s.opt.StoreInterval > 0 {
```
Функция должна срабатывать при включенном режиме синхронизации (`s.opt.StoreInterval == 0`) и должна НЕ срабатывать при s.opt.StoreInterval > 0

2024-08-24 22:47 UTC, avhitrov commented on cmd/server/main.go
> +			if err := storage.Backup(); err != nil {
```suggestion
			if err := storage.BackupPeriodically(); err != nil {
```
По заявленной логике (с учетом предложенных исправлений) `storage.Backup()` будет срабатывать каждый раз, когда включен синхронный бекап (StoreInterval == 0). В этом случае бекап будет консистентным, после шатдауна сервера новых записей в in-memory не появится. В случае, если бекап асинхронный (StoreInterval > 0), в процессе завершения работы он может действительно быть не консистентен состоянию in-memory и действительно необходимо будет сбросить данные на диск. Поэтому нужно дергать именно `BackupPeriodically`, так как эта функция срабатывает именно при условии StoreInterval > 0.

2024-08-25 07:05 UTC, merged

2024-08-25 07:05 UTC, andreevym commented on internal/storage/mem/mem.go
> +	if s.opt == nil || s.opt.BackupPath == "" || s.opt.StoreInterval == 0 {
готово

2024-08-25 07:05 UTC, andreevym commented on cmd/server/main.go
> +			if err := storage.Backup(); err != nil {
готово