Iteration 5
andreevym/metric-collector pull request #5
Opened 2023-10-09 20:29 UTC by andreevym

2023-10-11 10:37 UTC, capsulated requested changes
❌ - комментарии, которые обязательны к исправлению
⚠️ - комментарии, с которыми очень желательно разобраться и исправить

Плюс, обсудим эти моменты на 1-1

2023-10-11 10:37 UTC, capsulated commented on cmd/agent/env.go
> +type EnvConfig struct {
Конфиги тоже можно в отдельный пакет переместить

2023-10-11 10:37 UTC, capsulated commented on cmd/agent/main.go
> +var (
❌ Эти переменные и константы необходимо перенести в соответсвующий пакет. `cmd` - это инициализация и запуск приложения и каких-то особенностей реализации в  `cmd` быть не должно

2023-10-11 10:37 UTC, capsulated commented on cmd/agent/main.go
> +	ContentType = "text/plain"
❌ Это явно в хендлеры перенести нужно

2023-10-11 10:37 UTC, capsulated commented on cmd/agent/main.go
> +	flag.Parse()
Вот хорошо бы было весь парсинг и проверка конфигов была в отдельном пакете и методе, а здесь только вызов этого метода

2023-10-11 10:37 UTC, capsulated commented on cmd/agent/main.go
> +func sendMetricToServer(tickerReport *time.Ticker, metricServerURL string) {
⚠️ Очень желательно создать отдельный пакет для агента, так называемый воркер. Описывать его в main() пакета `cmd` плохая идея

2023-10-11 10:37 UTC, capsulated commented on internal/repository/repository.go
> +type Storage interface {
⚠️ Интерфейсы в go [обычно объявляются в пакете потребителя интерфейса](https://github.com/golang/go/wiki/CodeReviewComments#interfaces)

2023-10-11 10:37 UTC, capsulated commented on internal/handlers/server.go
> +type Server struct {
❌ Получается путаница с объектами - два сервера в приложении, в разных пакетах. Скорее всего текущий нужно переименовать.

Кажется, лишний объект. Его логика, скорее всего, должна быть скрыта в реализации хранилки. Или в отдельном пакете для метрик. Но точно не в хендлерах. Лучше полностью избавиться от этой структуры

2023-10-11 10:37 UTC, capsulated commented on internal/handlers/router.go
> +func Router(s Server) chi.Router {
⚠️ Очень важно разобраться, [когда используются указатели в ресивере](https://go.dev/doc/faq#methods_on_values_or_pointers), и когда указатели в выходных значениях. Чаще всего, это указатели, если это не простые типы

2023-10-11 10:37 UTC, capsulated commented on internal/handlers/router.go
> +		s.UpdateMetricHandler(),
Соответсвенно, если убрать из хендлера возвращение функции, то тут, скорее всего будет  так:
```go
r.Handle("/update/{metricType}/{metricName}/{metricValue}", s.UpdateMetricHandler)
```

2023-10-11 10:37 UTC, capsulated commented on internal/handlers/update_handler.go
> +	return func(w http.ResponseWriter, r *http.Request) {
Не совсем понятно, для чего возвращается функция (есть комментарий про это в роутере)

2023-10-11 10:37 UTC, capsulated commented on internal/model/metric.go
> +const (
В го не принято объявлять модели отдельно от их использования. Обычно, также как с интерфейсами: там где есть потребитель модели, там и объявляется

2023-10-17 15:15 UTC, andreevym commented on internal/model/metric.go
> +const (
теперь пакета model нет

2023-10-17 15:16 UTC, andreevym commented on internal/handlers/update_handler.go
> +	return func(w http.ResponseWriter, r *http.Request) {
исправил

2023-10-17 15:16 UTC, andreevym commented on internal/handlers/router.go
> +		s.UpdateMetricHandler(),
испавил. да, всё верно.

2023-10-17 15:17 UTC, andreevym commented on internal/handlers/router.go
> +func Router(s Server) chi.Router {
разобрался

2023-10-17 15:18 UTC, andreevym commented on internal/handlers/server.go
> +type Server struct {
переименован в ServiceHandlers

2023-10-17 15:18 UTC, andreevym commented on internal/handlers/server.go
> +type Server struct {
переименован в ServiceHandlers

2023-10-17 15:18 UTC, andreevym commented on internal/handlers/server.go
> +type Server struct {
переименован в ServiceHandlers

2023-10-17 15:19 UTC, andreevym commented on cmd/agent/main.go
> +func sendMetricToServer(tickerReport *time.Ticker, metricServerURL string) {
сделал отдельный пакет metric и туда перенес функции `sendByTickerAndAddress` и `pollLastMemStatByTicker`

2023-10-17 15:20 UTC, andreevym commented on cmd/agent/main.go
> +	flag.Parse()
постарался вынести в отдельный пакет config, правда получилось не очень красиво как по мне

2023-10-17 15:23 UTC, andreevym commented on cmd/agent/main.go
> +	ContentType = "text/plain"
исправил, перенес в хендлеры

2023-10-17 15:23 UTC, andreevym commented on cmd/agent/env.go
> +type EnvConfig struct {
исправил

2023-10-17 15:28 UTC, andreevym commented on cmd/agent/main.go
> +var (
исправил, перенес в отдельный пакет.

2023-10-18 14:47 UTC, capsulated commented on cmd/agent/main.go
> +	flag.Parse()
init() перед main() не особо красиво, а в остальном вроде всё ок

2023-10-18 14:52 UTC, capsulated approved these changes
Все комменты исправлены 🔥 Оставил пару новых комментариев, там совсем не критично. 

В следующем спринте будем смотреть , удобно ли получилось))

2023-10-18 14:52 UTC, capsulated commented on cmd/server/main.go
> +	config.ServerFlags()
да можно и в main() перенести как мне кажется

2023-10-18 14:52 UTC, capsulated commented on internal/multistorage/save.go
> +package multistorage
Какой-то странный пустой файл 😳

2023-10-18 16:22 UTC, andreevym commented on internal/multistorage/save.go
> +package multistorage
избавились от этого файла!

2023-10-18 16:30 UTC, andreevym commented on cmd/server/main.go
> +	config.ServerFlags()
готово

2023-10-18 16:30 UTC, merged